apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-ssd-nano-pc
  annotations:
    storageclass.kubernetes.io/is-default-class: true
provisioner: nfs-provisioner/nfs-ssd-nano-pc
parameters:
  archiveOnDelete: "true"
